### ISSUE TITLE
Often video connection is not work

### ISSUE THREAD

**Issue by ManoogD** [mslosarz/nextrtc-signaling-server#15]
We've created project which allow people to connect with each other and see each other.

Our logic is when people start conversation it sends http request to backend for checking is there anyone who exist and waits for conversation also or not. If it's not it sends signal 'Create' and wait for another person. Second person also works with this logic and when he presses button 'Start' he sends http request and he detects that already someone exists in conversation and send to backend 'Join' signal. 

From algoritm and logic everything is fine I think.
But there is a problem when, for example,  they talk and see each other and someone decides to leave conversation and after some time (let it be fast for example 5 sec) he wants to join again and we get problem. He can join and it sends 'Join' signal also they are connected but Video translation is not work and honestly we can't catch this bug in production.
Sometimes it works fine but from 10 times this bug appears 3-4 times. 

We have "Leave" button also, it appears when conversation from two people is created and they start see and talk. When person clicks "Leave" button it does "this.nextRTC.leave();"  action and when callback comes that connection is closed I open it again via initNextRtc(); And it works like this every time when I leave or press F5 button.

1) first Image shows how works perfect

![1](https://cloud.githubusercontent.com/assets/13423531/23587151/d7bc5e2c-01bf-11e7-8430-2c97f2dc2625.png)

2) when I start reconnect it should connect me to the same person. But we can't  see each other. By the way we can hear each other but no see. We don't know why.
![2](https://cloud.githubusercontent.com/assets/13423531/23587164/fce9bece-01bf-11e7-86a2-e58106c61b47.png)

3) this logs, please pay attention to what's happening after 'Join' signal. I mean nothing happens but it should make a lot of logs after that about candidate and so on. 

![dddddd](https://cloud.githubusercontent.com/assets/13423531/23587284/4f957a58-01c2-11e7-9d7d-eab8a422b133.png)

By the way, when every time person makes reconection sometimes it throws "java.io.IOException: An established connection was aborted by the software in the host machine" exception but anyway connection works fine. Maybe our bug is because of this? 

Could you give us advcie how to correct 'leave' from conversation please?

And please, if you avaliable in skype add me Kascheypro. Because we create project which is not open source and screens may break some policy our company.

Thank you!

**Comment by mslosarz** [comment]
First try to use latest nexrRTC.js (it is in nextrtc-js-client), I'll release 0.0.6 soon so please meanwhile use SNAPSHOT. In 0.0.5 sometimes spds exchange could be broken (when there was second try of setting up connection) If you have logs you can send it to my privat email and I'll analyze it

**Comment by mslosarz** [comment]
My e mail is m.slosarz at ahej.pl

**Comment by mslosarz** [comment]
Could you confirm that this issue is fixed in 0.0.6?

**Comment by ManoogD** [comment]
No, I'm sorry but it still exists. But we have a 'reconect' signal that detect that connection is not good and reconect it again. It works fine.
